In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\jason\Documents\Jerry\Studies\Jerry DSc\archive (2)\heart.csv")

In [3]:
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [4]:
df['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [5]:
df['ChestPainType'] = (
    df['ChestPainType'].replace(['ATA'],'0')
    .replace(['NAP'],'1')
    .replace(['ASY'],'2')
    .replace(['TA'],'3')
)
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M             0        140          289          0     Normal    172   
1   49   F             1        160          180          0     Normal    156   
2   37   M             0        130          283          0         ST     98   
3   48   F             2        138          214          0     Normal    108   
4   54   M             1        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [6]:
df['Sex'] = (
    df['Sex'].replace(['M'],'0')
    .replace(['F'],'1')
)
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   0             0        140          289          0     Normal    172   
1   49   1             1        160          180          0     Normal    156   
2   37   0             0        130          283          0         ST     98   
3   48   1             2        138          214          0     Normal    108   
4   54   0             1        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [7]:
df['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [8]:
df['RestingECG'] = (
    df['RestingECG'].replace(['Normal'],'0')
    .replace(['ST'],'1')
    .replace(['LVH'],'2')
)
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   0             0        140          289          0          0    172   
1   49   1             1        160          180          0          0    156   
2   37   0             0        130          283          0          1     98   
3   48   1             2        138          214          0          0    108   
4   54   0             1        150          195          0          0    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [9]:
df['ExerciseAngina'] = (
    df['ExerciseAngina'].replace(['N'],'0')
    .replace(['Y'],'1')
)
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   0             0        140          289          0          0    172   
1   49   1             1        160          180          0          0    156   
2   37   0             0        130          283          0          1     98   
3   48   1             2        138          214          0          0    108   
4   54   0             1        150          195          0          0    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              0      0.0       Up             0  
1              0      1.0     Flat             1  
2              0      0.0       Up             0  
3              1      1.5     Flat             1  
4              0      0.0       Up             0

In [10]:
df['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [11]:
df['ST_Slope'] = (
    df['ST_Slope'].replace(['Up'],'0')
    .replace(['Flat'],'1')
    .replace(['Down'],'2')
)
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   0             0        140          289          0          0    172   
1   49   1             1        160          180          0          0    156   
2   37   0             0        130          283          0          1     98   
3   48   1             2        138          214          0          0    108   
4   54   0             1        150          195          0          0    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              0      0.0        0             0  
1              0      1.0        1             1  
2              0      0.0        0             0  
3              1      1.5        1             1  
4              0      0.0        0             0

In [12]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [13]:
mean_value=df['Cholesterol'].mean()
mean_value

198.7995642701525

In [14]:
mean_value=df['RestingBP'].mean()
mean_value

132.39651416122004

In [15]:
print(df['RestingBP'].where(df['RestingBP'] == 0).count())

1


In [16]:
print(df['Cholesterol'].where(df['Cholesterol'] == 0).count())

172


In [17]:
df["Cholesterol"].replace(to_replace = 0, value = 198.80, inplace=True)
df["RestingBP"].replace(to_replace = 0, value = 132.40, inplace=True)

In [18]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.540741   236.047495    0.233115  136.809368   
std      9.432617   17.989932    56.240898    0.423046   25.460334   
min     28.000000   80.000000    85.000000    0.000000   60.000000   
25%     47.000000  120.000000   198.800000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [19]:
df.corr()

Age  RestingBP  Cholesterol  FastingBS     MaxHR   Oldpeak  \
Age           1.000000   0.263080     0.006398   0.198039 -0.382045  0.258612   
RestingBP     0.263080   1.000000     0.096524   0.067816 -0.109668  0.174215   
Cholesterol   0.006398   0.096524     1.000000  -0.061966  0.072643  0.059128   
FastingBS     0.198039   0.067816    -0.061966   1.000000 -0.131438  0.052698   
MaxHR        -0.382045  -0.109668     0.072643  -0.131438  1.000000 -0.160691   
Oldpeak       0.258612   0.174215     0.059128   0.052698 -0.160691  1.000000   
HeartDisease  0.282039   0.117930    -0.012339   0.267291 -0.400421  0.403951   

              HeartDisease  
Age               0.282039  
RestingBP         0.117930  
Cholesterol      -0.012339  
FastingBS         0.267291  
MaxHR            -0.400421  
Oldpeak           0.403951  
HeartDisease      1.000000

In [20]:
y=df['HeartDisease']
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [21]:
x=df.drop('HeartDisease', axis=1)
x

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   0             0      140.0        289.0          0          0   
1     49   1             1      160.0        180.0          0          0   
2     37   0             0      130.0        283.0          0          1   
3     48   1             2      138.0        214.0          0          0   
4     54   0             1      150.0        195.0          0          0   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   0             3      110.0        264.0          0          0   
914   68   0             2      144.0        193.0          1          0   
915   57   0             2      130.0        131.0          0          0   
916   57   1             0      130.0        236.0          0          2   
917   38   0             1      138.0        175.0          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
0      172              0      0.0        0  
1      156              0      1.0        1  
2       98              0      0.0        0  
3      108              1      1.5        1  
4      122              0      0.0        0  
..     ...            ...      ...      ...  
913    132              0      1.2        1  
914    141              0      3.4        1  
915    115              1      1.2        1  
916    174              0      0.0        1  
917    173              0      0.0        0  

[918 rows x 11 columns]

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [23]:
from sklearn.linear_model import LogisticRegression
clr = LogisticRegression()
clr.fit(x_train, y_train)
y_pred = clr.predict(x_test)
y_pred

C:\Users\jason\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [24]:
print(confusion_matrix(y_test, y_pred))
accuracy = metrics.accuracy_score(y_test, y_pred)
print(accuracy)
print(metrics.classification_report(y_test, y_pred))

[[ 85  15]
 [ 14 116]]
0.8739130434782608
              precision    recall  f1-score   support

           0       0.86      0.85      0.85       100
           1       0.89      0.89      0.89       130

    accuracy                           0.87       230
   macro avg       0.87      0.87      0.87       230
weighted avg       0.87      0.87      0.87       230



In [25]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)
y_pred2 = classifier.predict(x_test)

In [26]:
print(confusion_matrix(y_test, y_pred2))
accuracy = metrics.accuracy_score(y_test, y_pred2)
print(accuracy)
print(metrics.classification_report(y_test, y_pred2))

[[60 40]
 [35 95]]
0.6739130434782609
              precision    recall  f1-score   support

           0       0.63      0.60      0.62       100
           1       0.70      0.73      0.72       130

    accuracy                           0.67       230
   macro avg       0.67      0.67      0.67       230
weighted avg       0.67      0.67      0.67       230



In [27]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)
y_pred3 = dtc.predict(x_test)
y_pred3

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [28]:
print(confusion_matrix(y_test, y_pred3))
accuracy = metrics.accuracy_score(y_test, y_pred3)
print(accuracy)
print(metrics.classification_report(y_test, y_pred3))

[[ 82  18]
 [ 30 100]]
0.7913043478260869
              precision    recall  f1-score   support

           0       0.73      0.82      0.77       100
           1       0.85      0.77      0.81       130

    accuracy                           0.79       230
   macro avg       0.79      0.79      0.79       230
weighted avg       0.80      0.79      0.79       230



In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, n_estimators=100)
classifier_rf.fit(x_train, y_train)
y_pred4 = classifier_rf.predict(x_test)
y_pred4

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [30]:
print(confusion_matrix(y_test, y_pred4))
accuracy = metrics.accuracy_score(y_test, y_pred4)
print(accuracy)
print(metrics.classification_report(y_test, y_pred4))

[[ 86  14]
 [ 10 120]]
0.8956521739130435
              precision    recall  f1-score   support

           0       0.90      0.86      0.88       100
           1       0.90      0.92      0.91       130

    accuracy                           0.90       230
   macro avg       0.90      0.89      0.89       230
weighted avg       0.90      0.90      0.90       230



In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred5 = gnb.fit(x_train, y_train).predict(x_test)
y_pred5

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [32]:
print(confusion_matrix(y_test, y_pred5))
accuracy = metrics.accuracy_score(y_test, y_pred5)
print(accuracy)
print(metrics.classification_report(y_test, y_pred5))

[[ 86  14]
 [ 16 114]]
0.8695652173913043
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       100
           1       0.89      0.88      0.88       130

    accuracy                           0.87       230
   macro avg       0.87      0.87      0.87       230
weighted avg       0.87      0.87      0.87       230



In [33]:
df.tail()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45   0             3      110.0        264.0          0          0   
914   68   0             2      144.0        193.0          1          0   
915   57   0             2      130.0        131.0          0          0   
916   57   1             0      130.0        236.0          0          2   
917   38   0             1      138.0        175.0          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              0      1.2        1             1  
914    141              0      3.4        1             1  
915    115              1      1.2        1             1  
916    174              0      0.0        1             1  
917    173              0      0.0        0             0

In [34]:
df.tail(5)

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
913   45   0             3      110.0        264.0          0          0   
914   68   0             2      144.0        193.0          1          0   
915   57   0             2      130.0        131.0          0          0   
916   57   1             0      130.0        236.0          0          2   
917   38   0             1      138.0        175.0          0          0   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
913    132              0      1.2        1             1  
914    141              0      3.4        1             1  
915    115              1      1.2        1             1  
916    174              0      0.0        1             1  
917    173              0      0.0        0             0